<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <RootNamespace>RootNamespaceSpot</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Condition="'$(TargetFramework)' == 'net8.0'" Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <ProjectReference Include="../temper-core/TemperLang.Core.csproj"/>
  </ItemGroup>

</Project>
