#!/bin/bash
# Convenience to run a python script under the scripts directory.
# Requires `poetry` be installed and available in the path.

if [[ -z $1 ]]; then
    poetry run -C "$(dirname $0)"/scripts help
else
    poetry run -C "$(dirname $0)"/scripts "$@"
fi
