package lang.temper.kcodegen.functests

import lang.temper.common.temperEscaper
import lang.temper.log.FilePath.Companion.joinPathTo
import lang.temper.log.UNIX_FILE_SEGMENT_SEPARATOR

const val CONFIG_HEADER = """
# Temper Functional Test Suite

Autogenerated file, to update use `./gradlew kcodegen:up`, to update this header, see:
`kcodegen/src/commonMain/kotlin/lang/temper/kcodegen/functests/ConfigTemperTemplate.kt`.

"""

internal fun StringBuilder.ctmImport(test: TestModule) {
    val importSpecifier = buildString {
        append("./")
        test.relToResources.joinPathTo(this)
        if (this.endsWith(UNIX_FILE_SEGMENT_SEPARATOR)) { // Strip trailing '/'
            this.setLength(this.length - UNIX_FILE_SEGMENT_SEPARATOR.length)
        }
    }
    appendLine("    import(${temperEscaper.escape(importSpecifier)});")
}

internal const val CONFIG_FOOTER = ""
