package lang.temper.kcodegen.functests

import lang.temper.log.resolveFile

const val FT_ENUM_HEADER = """@file:Suppress("ktlint")

package lang.temper.tests

import lang.temper.log.MessageTemplate
import lang.temper.name.BackendId

/**
 * Autogenerated file, to update use `./gradlew kcodegen:up`, to update these docs, see:
 * `kcodegen/src/commonMain/kotlin/lang/temper/kcodegen/functests/FunctionalTestsTemplate.kt`.
 *
 * An enumeration of all functional tests for Temper backends.
 *
 * Adding a test involves creating a Temper module in `src/commonMain/resources` within
 * this subproject.
 *
 * Then rerun kcodegen to update:
 * - FunctionalTestSuiteI
 * - FunctionalTests
 *
 * If tests fail or pass on various backends, we can specify this as [IssueCheck] values for the enum entry.
 *
 * ```kotlin
 * TestEnumEntry(TestObjectItself, py(123), interp.ok)
 * ```
 *
 * Specify a check in [onlyPasses] if a backend is under development and most tests fail.
 *
 * Use [functionalTestStatus] once it's mostly complete and there are only a few
 * failures due to specific issues.
 */

enum class FunctionalTests(val test: FunctionalTestBase) {
"""

internal fun StringBuilder.ftEnumEntry(test: TestModule) {
    test.warning?.let {
        appendLine("    // $it")
    }
    val indent = "    " + if (test.disabled) "// " else { "" }
    val args = test.args
    val testFile = test.relToResources.resolveFile(test.testFile).quoted()
    if (args.isEmpty()) {
        appendLine("${indent}${test.enumName}(markdown($testFile, \"${test.enumName}\")),")
    } else {
        appendLine("${indent}${test.enumName}(")
        appendLine("$indent    markdown(")
        appendLine("$indent        $testFile,")
        appendLine("$indent        \"${test.enumName}\",")
        for (arg in args) {
            appendLine("$indent        $arg")
        }
        appendLine("$indent    ),")
        appendLine("${indent}),")
    }
}

const val FT_ENUM_FOOTER = """
    ;

    /** Check if this test should be run on this backend. */
    fun disposition(backend: BackendId): Disposition {
        return dispo(this, backend)
    }
}
"""
