package lang.temper.kcodegen.functests

const val FT_INTER_HEADER = """@file:Suppress("ktlint")

package lang.temper.tests
import lang.temper.common.console
import lang.temper.common.currents.CancelGroup
import lang.temper.name.BackendId
import org.junit.jupiter.api.Timeout
import kotlin.test.Test

typealias Ft = FunctionalTests

/**
 * Autogenerated file, to update use `./gradlew kcodegen:up`, to update these docs, see:
 * `kcodegen/src/commonMain/kotlin/lang/temper/kcodegen/functests/FunctionalTestSuiteITemplate.kt`.
 *
 * Has a method per test-case in [FunctionalTests] to make it easier to keep test suites up-do-date with
 * a test method per.  This makes for nicer test reports and provides IDE UI elements for easy
 * test running.
 *
 * All these tests must be defined here; backends do not have to define them. To inspect a specific test on a
 * backend, there are two options:
 *
 * 1. Override the method on the backend
 *    - Alt-Shift-O for Override methods
 *    - Select the test to override
 *    - Edit to run the desired test, e.g.
 *    ```kotlin
 *    @Test
 *    override fun helloWorld() = runFunctionalTest(FunctionalTests.HelloWorld)
 *    ```
 * 2. Manually edit a gradle configuration:
 *    - Run the "allTests" test
 *    - Control-Shift A and "Edit Configurations"
 *    - Duplicate the configuration created for "allTests"
 *    - Change the argument, e.g. `--tests "lang.temper.be.js.JsFunctionalTests.allTests"`
 *      to `--tests "lang.temper.be.js.JsFunctionalTests.helloWorld"`
 */
@Timeout(TIMEOUT)
interface FunctionalTestSuiteI {
    val cancelGroup: CancelGroup

    /** Runs a specific test. */
    fun runFunctionalTest(
        test: FunctionalTestBase,
        verbose: Boolean = false,
    )

    /** The backend this test runner is running against. */
    val backendId: BackendId

    fun runFunctionalTest(
        test: FunctionalTests,
        runOverride: Disposition? = null,
        verbose: Boolean = false,
    ) {
        if ((runOverride ?: test.disposition(backendId)) is Disposition.Skip) {
            console.info("Skipping ${'$'}{test.name}")
        } else {
            runFunctionalTest(test.test, verbose)
        }
    }

    /**
     * Test methods are updated via `./gradlew kcodegen:up`.
     */
"""

internal fun StringBuilder.ftInterMethod(test: TestModule) {
    test.warning ?. let { w -> appendLine("    // $w") }
    var six = "TODO: "
    for (todo in test.todos) {
        appendLine("    // $six$todo")
        six = "      "
    }
    val indent = "    " + if (test.disabled) "// " else { "" }
    appendLine("${indent}@Test")
    appendLine("${indent}fun ${test.methodName}() =")
    appendLine("$indent    runFunctionalTest(Ft.${test.enumName})")
}

internal const val FT_INTER_FOOTER = """}

private const val TIMEOUT = 60L
"""
