package lang.temper.ast

/**
 * Relates an [OutTree] subclass's properties to child indices.
 * This is used heavily by code generated by the *OutputGrammarCodeGenerator*.
 *
 * In a tree defined thus
 *
 *     "function" (id%Identifier || ()) "(" params%Pattern*", " ")" body%BlockStatement
 *
 * there are three child member relationships
 *
 * 1. An optional identifier, so a relationship that may return an [OutTree] or `null`
 * 2. A repeated pattern representing an input, so a *List* of trees.
 * 3. A required block statement representing the body.  A single [OutTree], never `null`.
 *
 * The [ChildMemberRelationships] for such a thing might look like
 *
 *     { n -> (n as Function).id },
 *     { n -> (n as Function).params },
 *     { n -> (n as Function).body },
 */
class ChildMemberRelationships(
    /**
     * Accessors for sub-lists of children.
     * Valid return values are:
     * - A single [OutTree] representing itself
     * - `null` representing the absence of any child.
     * - A list, assumed to be a `List<OutTree>` representing a run of adjacent children in order.
     */
    val accessors: List<(OutFormattable<*>) -> Any?>,
) {
    constructor(vararg accessors: (OutFormattable<*>) -> Any?) : this(accessors.toList())
}
