@file:lang.temper.common.Generated("FunctionalTestSuitener")
@file:Suppress("ktlint")

package lang.temper.tests

import lang.temper.log.MessageTemplate
import lang.temper.name.BackendId

/**
 * Autogenerated file, to update use `./gradlew kcodegen:up`, to update these docs, see:
 * `kcodegen/src/commonMain/kotlin/lang/temper/kcodegen/functests/FunctionalTestsTemplate.kt`.
 *
 * An enumeration of all functional tests for Temper backends.
 *
 * Adding a test involves creating a Temper module in `src/commonMain/resources` within
 * this subproject.
 *
 * Then rerun kcodegen to update:
 * - FunctionalTestSuiteI
 * - FunctionalTests
 *
 * If tests fail or pass on various backends, we can specify this as [IssueCheck] values for the enum entry.
 *
 * ```kotlin
 * TestEnumEntry(TestObjectItself, py(123), interp.ok)
 * ```
 *
 * Specify a check in [onlyPasses] if a backend is under development and most tests fail.
 *
 * Use [functionalTestStatus] once it's mostly complete and there are only a few
 * failures due to specific issues.
 */

enum class FunctionalTests(val test: FunctionalTestBase) {
    AlgosFibonacci(markdown("algos/fibonacci/fibonacci.temper.md", "AlgosFibonacci")),
    AlgosHelloFromClassToTop(markdown("algos/hello-from-class-to-top/hello-from-class-to-top.temper.md", "AlgosHelloFromClassToTop")),
    AlgosHelloWorld(markdown("algos/hello-world/hello-world.temper.md", "AlgosHelloWorld")),
    AlgosHelloWorldObject(markdown("algos/hello-world-object/hello-world-object.temper.md", "AlgosHelloWorldObject")),
    AlgosMyersDiff(markdown("algos/myers-diff/myers-diff.temper.md", "AlgosMyersDiff")),
    CastsAsExpr(markdown("casts/as-expr/as-expr.temper.md", "CastsAsExpr")),
    CastsSpecific(markdown("casts/specific/specific.temper.md", "CastsSpecific")),
    ClassesAngleCall(markdown("classes/angle-call/angle-call.temper.md", "ClassesAngleCall")),
    ClassesCallOverrideFromSubtype(markdown("classes/call-override-from-subtype/call-override-from-subtype.temper.md", "ClassesCallOverrideFromSubtype")),
    ClassesDirectGetter(markdown("classes/direct-getter/direct-getter.temper.md", "ClassesDirectGetter")),
    ClassesInheritedGetter(markdown("classes/inherited-getter/inherited-getter.temper.md", "ClassesInheritedGetter")),
    ClassesObjectLiterals(markdown("classes/object-literals/object-literals.temper.md", "ClassesObjectLiterals")),
    ClassesPrivateMethod(markdown("classes/private-method/private-method.temper.md", "ClassesPrivateMethod")),
    ClassesPropertyOrder(markdown("classes/property-order/property-order.temper.md", "ClassesPropertyOrder")),
    ClassesSetters(markdown("classes/setters/setters.temper.md", "ClassesSetters")),
    ClassesStaticProperties(markdown("classes/static-properties/static-properties.temper.md", "ClassesStaticProperties")),
    ClassesStaticPropertiesScope(markdown("classes/static-properties-scope/static-properties-scope.temper.md", "ClassesStaticPropertiesScope")),
    ControlFlowActorRun(markdown("control-flow/actor-run/actor-run.temper.md", "ControlFlowActorRun")),
    ControlFlowAsync(markdown("control-flow/async/async.temper.md", "ControlFlowAsync")),
    ControlFlowBubble(markdown("control-flow/bubble/bubble.temper.md", "ControlFlowBubble")),
    ControlFlowIfReturn(markdown("control-flow/if-return/if-return.temper.md", "ControlFlowIfReturn")),
    ControlFlowLoopReenterable(markdown("control-flow/loop-reenterable/loop-reenterable.temper.md", "ControlFlowLoopReenterable")),
    ControlFlowLoops(markdown("control-flow/loops/loops.temper.md", "ControlFlowLoops")),
    FunctionsAsValues(markdown("functions/as-values/as-values.temper.md", "FunctionsAsValues")),
    FunctionsConstructorCallbacks(markdown("functions/constructor-callbacks/constructor-callbacks.temper.md", "FunctionsConstructorCallbacks")),
    FunctionsDefaulting(markdown("functions/defaulting/defaulting.temper.md", "FunctionsDefaulting")),
    FunctionsLocals(markdown("functions/locals/locals.temper.md", "FunctionsLocals")),
    FunctionsNamedArgs(markdown("functions/named-args/named-args.temper.md", "FunctionsNamedArgs")),
    FunctionsRestFormal(markdown("functions/rest-formal/rest-formal.temper.md", "FunctionsRestFormal")),
    FunctionsSimpleLocals(markdown("functions/simple-locals/simple-locals.temper.md", "FunctionsSimpleLocals")),
    ImportsFunctions(markdown("imports/functions/functions.temper.md", "ImportsFunctions")),
    ImportsTypes(markdown("imports/types/types.temper.md", "ImportsTypes")),
    ImportsValues(markdown("imports/values/values.temper.md", "ImportsValues")),
    InterfacesEmpty(markdown("interfaces/empty/empty.temper.md", "InterfacesEmpty")),
    InterfacesPropertyMembers(markdown("interfaces/property-members/property-members.temper.md", "InterfacesPropertyMembers")),
    InterfacesPureVirtual(markdown("interfaces/pure-virtual/pure-virtual.temper.md", "InterfacesPureVirtual")),
    NamesNonascii(markdown("names/nonascii/nonascii.temper.md", "NamesNonascii")),
    RegexMatch(markdown("regex/match/match.temper.md", "RegexMatch")),
    RegexZeroAdvance(markdown("regex/zero-advance/zero-advance.temper.md", "RegexZeroAdvance")),
    RegressionMinimalRepro(markdown("regression/minimal-repro/minimal-repro.temper.md", "RegressionMinimalRepro")),
    SemanticsBroken(
        markdown(
            "semantics/broken/broken.temper.md",
            "SemanticsBroken",
            allowedErrors = setOf(
                "BecauseNameUndeclared",
                MessageTemplate.IllegalAssignment.name,
                MessageTemplate.SignatureInputMismatch.name,
                MessageTemplate.CannotTranslate.name,
            ),
            expectRunFailure = true,
        ),
    ),
    SemanticsConstness(markdown("semantics/constness/constness.temper.md", "SemanticsConstness")),
    SemanticsMutuallyReferencingTypes(markdown("semantics/mutually-referencing-types/mutually-referencing-types.temper.md", "SemanticsMutuallyReferencingTypes")),
    SemanticsTypeCheckedLocals(
        markdown(
            "semantics/type-checked-locals/type-checked-locals.temper.md",
            "SemanticsTypeCheckedLocals",
            allowedErrors = setOf(
                MessageTemplate.ExpectedSubType.name,
                MessageTemplate.IllegalAssignment.name,
                MessageTemplate.ExpectedFunctionType.name,
            ),
        ),
    ),
    TestingAsserts(
        markdown(
            "testing/asserts/asserts.temper.md",
            "TestingAsserts",
            runAsTest = true,
            expectedFailures = mapOf(
                "a failing test" to """because it's wrong, expected helper.i == (2) not (3), expected s == (hi) not (bye)""",
            ),
        ),
    ),
    TypesDate(markdown("types/date/date.temper.md", "TypesDate")),
    TypesDenseBitVector(markdown("types/dense-bit-vector/dense-bit-vector.temper.md", "TypesDenseBitVector")),
    TypesDeque(markdown("types/deque/deque.temper.md", "TypesDeque")),
    TypesFloatBasics(markdown("types/float/basics/basics.temper.md", "TypesFloatBasics")),
    TypesFloatOps(markdown("types/float/ops/ops.temper.md", "TypesFloatOps")),
    TypesIntBasics(markdown("types/int/basics/basics.temper.md", "TypesIntBasics")),
    TypesIntLimits(markdown("types/int/limits/limits.temper.md", "TypesIntLimits")),
    TypesJsonSyntaxTree(markdown("types/json-syntax-tree/json-syntax-tree.temper.md", "TypesJsonSyntaxTree")),
    TypesListEmpty(markdown("types/list/empty/empty.temper.md", "TypesListEmpty")),
    TypesListOperations(markdown("types/list/operations/operations.temper.md", "TypesListOperations")),
    TypesListReduce(markdown("types/list/reduce/reduce.temper.md", "TypesListReduce")),
    TypesListSorting(markdown("types/list/sorting/sorting.temper.md", "TypesListSorting")),
    TypesMap(markdown("types/map/map.temper.md", "TypesMap")),
    TypesNetresponse(markdown("types/netresponse/netresponse.temper.md", "TypesNetresponse")),
    TypesStringBuild(markdown("types/string/build/build.temper.md", "TypesStringBuild")),
    TypesStringIndices(markdown("types/string/indices/indices.temper.md", "TypesStringIndices")),
    TypesStringIsEmpty(markdown("types/string/is-empty/is-empty.temper.md", "TypesStringIsEmpty")),
    TypesStringRead(markdown("types/string/read/read.temper.md", "TypesStringRead")),

    ;

    /** Check if this test should be run on this backend. */
    fun disposition(backend: BackendId): Disposition {
        return dispo(this, backend)
    }
}
