package lang.temper.tests

import lang.temper.common.affectedByIssue11
import lang.temper.common.affectedByIssue33
import lang.temper.common.kotlinBackend
import lang.temper.log.FilePath
import lang.temper.log.UNIX_FILE_SEGMENT_SEPARATOR
import lang.temper.log.filePath
import lang.temper.log.plus
import lang.temper.name.BackendId

/**
 * Tests are a `.temper.md` file with the expected stdout, so we don't create a separate object for each.
 * This assumes you're putting it under the test resources, and that it will import other resources.
 *
 * Invocations of this function are autogenerated by kcodegen.
 *
 * This function takes the path within [ModulePaths.testResourcesPath] to the `.temper.md` file.
 * Note that, by convention, the test-name should match its directory name.
 *
 * ```kotlin
 * markdown("all-tests-need-a-directory/test-name/test-name.temper.md")
 * ```
 *
 * The code generation looks for arguments to pass to this function in the form of:
 *
 * ```text
 * @meta:arg expectedFailures = mapOf(
 * @meta:arg     "foo" to "bar"
 * @meta:arg ),
 * ```
 *
 * Arguments will have trailing commas added.
 */
internal fun markdown(
    path: String,
    testName: String,
    runAsTest: Boolean = false,
    expectRunFailure: Boolean = false,
    expectedFailures: Map<String, String> = emptyMap(),
    allowedErrors: Set<String> = emptySet(),
): MarkdownFileBasedFunctionalTestBase = MarkdownFileBasedFunctionalTestBaseImpl(
    path = path,
    testName = testName,
    runAsTest = runAsTest,
    expectRunFailure = expectRunFailure,
    expectedTestFailures = expectedFailures,
    allowedErrors = allowedErrors,
)

private class MarkdownFileBasedFunctionalTestBaseImpl(
    val path: String,
    override val testName: String,
    override val runAsTest: Boolean,
    override val expectRunFailure: Boolean,
    override val expectedTestFailures: Map<String, String>,
    override val allowedErrors: Set<String>,
) : MarkdownFileBasedFunctionalTestBase() {
    override val projectPath: FilePath =
        ModulePaths.testResourcesPath + filePath(path.split(UNIX_FILE_SEGMENT_SEPARATOR))

    /**
     * Helps point [lang.temper.tests.AllTestsTest.updateFunctionalTestMatrix] to the actual test content.
     * If you write your own object and give it a standard name, you don't need to override this.
     */
    override val sourcePath = projectPath
}

/** A determination of whether a test should be run or skipped. */
sealed class Disposition {
    /** This test is expected to succeed. */
    object Run : Disposition()

    /** This test is known to fail, and this is tracked by the given issues. */
    class Skip(val issues: List<Int>) : Disposition() {
        constructor(vararg issues: Int) : this(issues.toList())
    }
}

/**
 * A function that inspects the backend ID (or possibly the build platform) to determine if a test should be run.
 * See the shorthand syntax [BackendId.invoke] and [BackendId.ok].
 */
typealias IssueCheck = (BackendId) -> Disposition?

@Suppress("MagicNumber") // Bug ID
val kotlinMultiplatformIssue: IssueCheck = {
    when {
        kotlinBackend.affectedByIssue33 -> Disposition.Skip(33)
        kotlinBackend.affectedByIssue11 -> Disposition.Skip(11)
        else -> null
    }
}

/**
 * Conveniences to create [IssueCheck]s.
 */
internal val interp = BackendId("interp")
internal val csharp = BackendId("csharp")
internal val java = BackendId("java")
internal val java8 = BackendId("java8")
internal fun javas(vararg issues: Int): IssueCheck = {
    if (it == java || it == java8) {
        Disposition.Skip(issues.toList())
    } else {
        Disposition.Run
    }
}
internal fun staticallyTypeds(vararg issues: Int): IssueCheck = { backendId ->
    when (backendId) {
        cpp, csharp, java, java8, rust -> Disposition.Skip(issues.toList())
        else -> Disposition.Run
    }
}
internal val cpp03 = BackendId("cpp03")
internal val cpp = BackendId("cpp")
internal val js = BackendId("js")
internal val lua = BackendId("lua")
internal val py = BackendId("py")
internal val mypyc = BackendId("mypyc")
internal val rust = BackendId("rust")

/** The expression `py(352)` indicates that the [py] backend is expected to fail with issue 352. */
internal operator fun BackendId.invoke(vararg issue: Int): IssueCheck = {
    if (it == this) { Disposition.Skip(*issue) } else { null }
}

/**
 * The expression `java.ok` indicates that the [java] backend is expected to pass.
 * This is typically to override an entry in [globalIssues].
 */
internal val BackendId.ok: IssueCheck get() = {
    if (it == this) { Disposition.Run } else { null }
}

/** Used to terminate the list of issue checks. */
internal val defaultToRun: IssueCheck = { Disposition.Run }
